name: SettlerCraft-StructureAPI
main: com.chingo247.structurecraft.bukkit.BKStructureAPIPlugin
version: 2.2.0
author: Chingo247
description: Create structures by placing schematics.
depend: [WorldEdit, AsyncWorldEdit, SettlerCraft-Core]

    


          
        
                
            

                    
                    

            
               
               