name: StructureCraft-Rollback
main: com.chingo247.structurecraft.rollback.StructureCraftRollbackPlugin
version: 2.2.0
author: Chingo247
description: BlockLogger for Bukkit
depend: [SettlerCraft-StructureAPI, BlocksHub]
    


          
        
                
            

                    
                    

            
               
               