name: StructureAPI-Towny
main: com.chingo247.structureapi.towny.plugin.StructureAPITowny
version: 2.2.0
author: Chingo247
description: Towny support for StructureAPI
depend: [SettlerCraft-StructureAPI, Towny]
          
        
                
            

                    
                    

            
               
               