name: SettlerCraft-StructureAPI
main: com.chingo247.structureapi.bukkit.BKStructureAPIPlugin
version: 3.0.0
author: Chingo247
description: Create structures by placing schematics.
depend: [WorldEdit, SettlerCraft-Core]
soft-depend: [AsyncWorldEdit, FastAsyncWorldEdit]
    


          
        
                
            

                    
                    

            
               
               