# The version of this config
# DO NOT CHANGE
version: 2.3.0

# Protection configs
protection:
    # The time in minutes that need to pass before the protection of a structure will expire
    # Negative value (e.g. -1) means infinite amount of time
    expires: -1
